# Generated by Django 4.2.3 on 2023-07-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='poster/')),
                ('name', models.CharField(max_length=200)),
                ('japanese_name', models.CharField(blank=True, max_length=200, null=True)),
                ('premiere', models.DateField(default=datetime.date.today)),
                ('episodes', models.PositiveSmallIntegerField(default=24)),
                ('status', models.CharField(choices=[('ongoing', 'Онгоинг'), ('released', 'Вышел')], max_length=20)),
                ('season', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
            ],
        ),
    ]
